export enum Role {
  Radiologist = 'radiologist',
  Physician = 'physician',
  Admin = 'admin',
  Auditor = 'auditor',
  MlEngineer = 'ml_engineer',
  SuperAdmin = 'super_admin',
}

export const RolePermissions = {
  [Role.Radiologist]: [
    'upload_image',
    'view_image',
    'request_inference',
    'view_ai_result',
    'review_ai',
    'confirm_ai',
    'override_ai',
    'provide_feedback',
  ],
  [Role.Physician]: [
    'upload_image',
    'view_image',
    'request_inference',
    'view_ai_result',
    'review_ai',
    'confirm_ai',
    'override_ai',
    'provide_feedback',
  ],
  [Role.Admin]: [
    'manage_users',
    'manage_roles',
    'configure_system',
    'view_system_health',
    'access_audit_logs',
  ],
  [Role.Auditor]: [
    'read_audit_logs',
    'view_config',
    'view_user_activity',
  ],
  [Role.MlEngineer]: [
    'deploy_model',
    'update_model',
    'view_model_metrics',
    'view_model_logs',
  ],
  [Role.SuperAdmin]: [
    'upload_image',
    'view_image',
    'request_inference',
    'view_ai_result',
    'review_ai',
    'confirm_ai',
    'override_ai',
    'provide_feedback',
    'manage_users',
    'manage_roles',
    'configure_system',
    'view_system_health',
    'access_audit_logs',
    'read_audit_logs',
    'view_config',
    'view_user_activity',
    'deploy_model',
    'update_model',
    'view_model_metrics',
    'view_model_logs',
    // Add any additional permissions here
  ],
};
